### ISSUE TITLE
Missing Settings class

### ISSUE THREAD

**Issue by codesista** [regularjack/wp-plugin-boilerplate#1]
The Admin class [calls a constructor for a Settings class](https://github.com/regularjack/wp-plugin-boilerplate/blob/master/src/Admin/Admin.php#L15) that isn't included anywhere in the code. Or did I miss it? What is that class supposed to do exactly?

**Comment by psrpinto** [comment]
Thanks for reporting this. That seems to have been been committed by accident, I just removed it in 61b12391076a3d610bc00ec9d1d561697dbcda77.

To be honest, this is kind of a work in progress, I wasn't expecting people to start using it yet. I'll be improving it in the next few days so that it reaches a stable state.
